### ISSUE TITLE
Error 500 when trying to load an invalid format

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#1064]
If you try to load an nonexistent resource with an extension like https://mumuki.io/foo.txt, you will get a 500 error.

**Comment by flbulgarelli** [comment]
The error you get in the server logs is similar to this: 

```
E, [2018-05-07T17:56:36.621727 #15] ERROR -- : [cbb2ec75-3aa7-47c4-a580-f3982628fae7] Internal server error: Missing template errors/not_found with {:locale=>[:es, :en], :formats=>[:svg], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :jbuilder]}. Searched in:
  * "/var/www/academia/app/views"
  * "/usr/local/bundle/gems/bootstrap-kaminari-views-0.0.5/app/views"
  * "/usr/local/bundle/gems/kaminari-0.17.0/app/views"
  * "/usr/local/bundle/gems/mumuki-laboratory-5.2.0/app/views"

/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/path_set.rb:46:in `find'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/lookup_context.rb:116:in `find'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:38:in `determine_template'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:8:in `render'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:42:in `render_template'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:23:in `render'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/rendering.rb:103:in `_render_template'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/rendering.rb:83:in `render_to_body'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
/usr/local/bundle/gems/actionpack-5.1.6/lib/abstract_controller/rendering.rb:24:in `render'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:36:in `render'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
```
