### ISSUE TITLE
Error 500 al ingresar a un ejercicio en primaria sin estar logueado

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-laboratory#1205]
Por ejemplo, acá: 

https://primaria.mumuki.io/exercises/5116-una-heladeria-con-alternativas-hay-palito-bombon-helado-mas-sabor

Probablemente sea consecuencia de #1175

**Comment by julian-berbel** [comment]
```
E, [2018-09-24T15:55:22.202150 #26] ERROR -- : [19511727-b0c7-4d05-b5d2-900497003c6a] Internal server error: undefined method `status' for nil:NilClass 
/usr/local/bundle/gems/mumuki-laboratory-5.9.1/app/views/layouts/_kids.html.erb:20:in `__usr_local_bundle_gems_mumuki_laboratory_______app_views_layouts__kids_html_erb___1287633924470652099_46306700'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/template.rb:157:in `block in render'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/template.rb:352:in `instrument_render_template'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/template.rb:155:in `render'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:310:in `render'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:47:in `render_partial'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:21:in `render'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/helpers/rendering_helper.rb:32:in `render'
/usr/local/bundle/gems/mumuki-laboratory-5.9.1/app/views/layouts/exercise_inputs/layouts/_input_kids.html.erb:14:in `block in __usr_local_bundle_gems_mumuki_laboratory_______app_views_layouts_exercise_inputs_layouts__input_kids_html_erb___2549422528039989471_46505140'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/helpers/capture_helper.rb:39:in `capture'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/helpers/capture_helper.rb:153:in `content_for'
/usr/local/bundle/gems/mumuki-laboratory-5.9.1/app/views/layouts/exercise_inputs/layouts/_input_kids.html.erb:1:in `__usr_local_bundle_gems_mumuki_laboratory_______app_views_layouts_exercise_inputs_layouts__input_kids_html_erb___2549422528039989471_46505140'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/template.rb:157:in `block in render'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/template.rb:352:in `instrument_render_template'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/template.rb:155:in `render'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:310:in `render'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:47:in `render_partial'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/helpers/rendering_helper.rb:35:in `render'
/usr/local/bundle/gems/mumuki-laboratory-5.9.1/app/helpers/exercise_input_helper.rb:3:in `render_exercise_input_layout'
/usr/local/bundle/gems/mumuki-laboratory-5.9.1/app/views/exercises/show.html.erb:44:in `__usr_local_bundle_gems_mumuki_laboratory_______app_views_exercises_show_html_erb___3117649790771226316_30736720'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/template.rb:157:in `block in render'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/template.rb:352:in `instrument_render_template'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/template.rb:155:in `render'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:50:in `render_template'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:14:in `render'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:42:in `render_template'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:23:in `render'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/rendering.rb:103:in `_render_template'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/rendering.rb:83:in `render_to_body'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
/usr/local/bundle/gems/actionpack-5.1.6/lib/abstract_controller/rendering.rb:24:in `render'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:36:in `render'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/usr/local/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:43:in `render'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/implicit_render.rb:33:in `default_render'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/basic_implicit_render.rb:4:in `block in send_action'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/basic_implicit_render.rb:4:in `tap'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/usr/local/bundle/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:186:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/bundle/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/rescue.rb:20:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/usr/local/bundle/gems/activerecord-5.1.6/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/usr/local/bundle/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:124:in `process'
/usr/local/bundle/gems/actionview-5.1.6/lib/action_view/rendering.rb:30:in `process'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal.rb:189:in `dispatch'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_controller/metal.rb:253:in `dispatch'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33:in `each'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33:in `serve'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:844:in `call'
/usr/local/bundle/gems/omniauth-1.4.3/lib/omniauth/strategy.rb:186:in `call!'
/usr/local/bundle/gems/omniauth-1.4.3/lib/omniauth/strategy.rb:164:in `call'
/usr/local/bundle/gems/omniauth-1.4.3/lib/omniauth/strategy.rb:186:in `call!'
/usr/local/bundle/gems/omniauth-1.4.3/lib/omniauth/strategy.rb:164:in `call'
/usr/local/bundle/gems/omniauth-1.4.3/lib/omniauth/strategy.rb:403:in `call_app!'
/usr/local/bundle/gems/omniauth-saml-1.10.1/lib/omniauth/strategies/saml.rb:89:in `other_phase'
/usr/local/bundle/gems/omniauth-1.4.3/lib/omniauth/strategy.rb:185:in `call!'
/usr/local/bundle/gems/omniauth-1.4.3/lib/omniauth/strategy.rb:164:in `call'
/usr/local/bundle/gems/omniauth-1.4.3/lib/omniauth/strategy.rb:186:in `call!'
/usr/local/bundle/gems/omniauth-1.4.3/lib/omniauth/strategy.rb:164:in `call'
/usr/local/bundle/gems/omniauth-1.4.3/lib/omniauth/builder.rb:63:in `call'
/usr/local/bundle/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'
/usr/local/bundle/gems/rack-2.0.5/lib/rack/conditional_get.rb:25:in `call'
/usr/local/bundle/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
/usr/local/bundle/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
/usr/local/bundle/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:97:in `run_callbacks'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/usr/local/bundle/gems/railties-5.1.6/lib/rails/rack/logger.rb:36:in `call_app'
/usr/local/bundle/gems/railties-5.1.6/lib/rails/rack/logger.rb:24:in `block in call'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:26:in `tagged'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/tagged_logging.rb:69:in `tagged'
/usr/local/bundle/gems/railties-5.1.6/lib/rails/rack/logger.rb:24:in `call'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/usr/local/bundle/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
/usr/local/bundle/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
/usr/local/bundle/gems/activesupport-5.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/middleware/static.rb:125:in `call'
/usr/local/bundle/gems/actionpack-5.1.6/lib/action_dispatch/middleware/static.rb:125:in `call'
/usr/local/bundle/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
/usr/local/bundle/gems/railties-5.1.6/lib/rails/engine.rb:522:in `call'
/usr/local/bundle/gems/puma-3.11.4/lib/puma/configuration.rb:225:in `call'
/usr/local/bundle/gems/puma-3.11.4/lib/puma/server.rb:632:in `handle_request'
/usr/local/bundle/gems/puma-3.11.4/lib/puma/server.rb:446:in `process_client'
/usr/local/bundle/gems/puma-3.11.4/lib/puma/server.rb:306:in `block in run'
/usr/local/bundle/gems/puma-3.11.4/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```
